language: node_js

node_js:
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g coveralls

before_install:
  - "npm install -g npm@latest"

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage